# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI Lucee 6

on: [push, pull_request,workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
     sql-server:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          MSSQL_PID: Express
          ACCEPT_EULA: Y
          SA_PASSWORD: Lucee!1433 # password must be complex or the service won't start
        ports:
          - 1433:1433
        options: --health-cmd="/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P ${SA_PASSWORD} -Q 'SELECT 1' || exit 1"  --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      luceeVersion: light-6.1.0.243
      luceeVersionQuery: 6/stable/light

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: lucee-mssql
        restore-keys: |
          ${{ runner.os }}-m2
          maven-cache
    - name: Cache Lucee files
      uses: actions/cache@v4
      with:
        path: _actions/lucee/script-runner/main/lucee-download-cache
        key: lucee-downloads
        restore-keys: |
          lucee-downloads
    - name: Build extension-jdbc-mssql with Ant
      run: ant -noinput -verbose -buildfile build.xml
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mssql-lex
        path: dist/*.lex
    - name: Checkout Lucee
      uses: actions/checkout@v4
      with:
        repository: lucee/lucee
        path: lucee
    - name: Run Lucee Test Suite, labels="mssql"
      uses: lucee/script-runner@main
      with:
        webroot: ${{ github.workspace }}/lucee/test
        execute: /bootstrap-tests.cfm
        luceeVersion: ${{ env.luceeVersion }}
        luceeVersionQuery: ${{ env.luceeVersionQuery }}
        extensionDir: ${{ github.workspace }}/dist
        extensions:
      env:
        testLabels: mssql
        MSSQL_SERVER: localhost
        MSSQL_USERNAME: sa
        MSSQL_PASSWORD: Lucee!1433
        MSSQL_PORT: 1433
        MSSQL_DATABASE: master
